from typing import Tuple, Dict, Any

def main() -> None: ...
def make_parsers() -> Tuple[Namespace, ArgParser] : ...
def do_task(args: Namespace) -> None: ...
def get_data() -> Dict: ...
def get_id(data: Dict) -> int: ...
def add_task(item: str, task_id: int, data: Dict) -> None: ...
def delete_task(task_id: int, data: Dict) -> None: ...
def sort_dict_data(task_dict: Tuple[str, Dict[str, Any]]) -> None: ...
def list_tasks(data: Dict) -> None: ...
def report_error(message: str, error_type: str = None) -> None: ...
